extend type Bookmark {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Bookmark", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Bookmark`.`garment`. It must match the value of `Garment`.`id`. See `@ref` for how to customize it.
  """
  garmentId: UUID! @fdc_generated(from: "Bookmark.garment", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Bookmark`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Bookmark.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Contribution {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Contribution", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Contribution`.`garment`. It must match the value of `Garment`.`id`. See `@ref` for how to customize it.
  """
  garmentId: UUID! @fdc_generated(from: "Contribution.garment", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Contribution`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Contribution.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Era {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Era", purpose: IMPLICIT_KEY_FIELD)
}
extend type Garment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Garment", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Garment`.`era`. It must match the value of `Era`.`id`. See `@ref` for how to customize it.
  """
  eraId: UUID! @fdc_generated(from: "Garment.era", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
